<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from uk.co.compucorp.membershipextrasimporterapi/xml/schema/CRM/Membershipextrasimporterapi/RecurringDonationImporter.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 */
use CRM_Membershipextrasimporterapi_ExtensionUtil as E;

/**
 * Database access object for the RecurringDonationImporter entity.
 */
class CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'recurringdonationimporter_fake_entity';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_external_id;

  /**
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $first_name;

  /**
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $last_name;

  /**
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $email;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $recurring_contribution_external_id;

  /**
   * @var float|string
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $recurring_contribution_amount;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $recurring_contribution_currency;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $recurring_contribution_frequency_unit;

  /**
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $recurring_contribution_cycle_day;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $recurring_contribution_start_date;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $recurring_contribution_next_sched_date;

  /**
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $recurring_contribution_financial_type;

  /**
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $recurring_contribution_payment_instrument;

  /**
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $recurring_contribution_description;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $gocardless_mandate_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'recurringdonationimporter_fake_entity';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Recurring Donation Importers') : E::ts('Recurring Donation Importer');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Id'),
          'description' => E::ts('Unique ID'),
          'required' => TRUE,
          'where' => 'recurringdonationimporter_fake_entity.id',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Id"),
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact Id'),
          'where' => 'recurringdonationimporter_fake_entity.contact_id',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Contact Id"),
          ],
          'add' => NULL,
        ],
        'contact_external_id' => [
          'name' => 'contact_external_id',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Contact External Id'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'recurringdonationimporter_fake_entity.contact_external_id',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Contact External Id"),
          ],
          'add' => NULL,
        ],
        'first_name' => [
          'name' => 'first_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('First Name'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'recurringdonationimporter_fake_entity.first_name',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("First Name"),
          ],
          'add' => NULL,
        ],
        'last_name' => [
          'name' => 'last_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Last Name'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'recurringdonationimporter_fake_entity.last_name',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Last Name"),
          ],
          'add' => NULL,
        ],
        'email' => [
          'name' => 'email',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Email'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'recurringdonationimporter_fake_entity.email',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Email"),
          ],
          'add' => NULL,
        ],
        'recurring_contribution_external_id' => [
          'name' => 'recurring_contribution_external_id',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Recurring Contribution External Id'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'recurringdonationimporter_fake_entity.recurring_contribution_external_id',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Recurring Contribution External Id"),
          ],
          'add' => NULL,
        ],
        'recurring_contribution_amount' => [
          'name' => 'recurring_contribution_amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Recurring Contribution Amount'),
          'required' => TRUE,
          'precision' => [
            20,
            2,
          ],
          'where' => 'recurringdonationimporter_fake_entity.recurring_contribution_amount',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Recurring Contribution Amount"),
          ],
          'add' => NULL,
        ],
        'recurring_contribution_currency' => [
          'name' => 'recurring_contribution_currency',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Recurring Contribution Currency'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'recurringdonationimporter_fake_entity.recurring_contribution_currency',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Recurring Contribution Currency"),
          ],
          'add' => NULL,
        ],
        'recurring_contribution_frequency_unit' => [
          'name' => 'recurring_contribution_frequency_unit',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Recurring Contribution Frequency Unit'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'recurringdonationimporter_fake_entity.recurring_contribution_frequency_unit',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Recurring Contribution Frequency Unit"),
          ],
          'add' => NULL,
        ],
        'recurring_contribution_cycle_day' => [
          'name' => 'recurring_contribution_cycle_day',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Recurring Contribution Cycle Day'),
          'where' => 'recurringdonationimporter_fake_entity.recurring_contribution_cycle_day',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Recurring Contribution Cycle Day"),
          ],
          'add' => NULL,
        ],
        'recurring_contribution_start_date' => [
          'name' => 'recurring_contribution_start_date',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Recurring Contribution Start Date'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'recurringdonationimporter_fake_entity.recurring_contribution_start_date',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Recurring Contribution Start Date"),
          ],
          'add' => NULL,
        ],
        'recurring_contribution_next_sched_date' => [
          'name' => 'recurring_contribution_next_sched_date',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Recurring Contribution Next Scheduled Date'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'recurringdonationimporter_fake_entity.recurring_contribution_next_sched_date',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Recurring Contribution Next Scheduled Date"),
          ],
          'add' => NULL,
        ],
        'recurring_contribution_financial_type' => [
          'name' => 'recurring_contribution_financial_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Recurring Contribution Financial Type'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'recurringdonationimporter_fake_entity.recurring_contribution_financial_type',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Recurring Contribution Financial Type"),
          ],
          'add' => NULL,
        ],
        'recurring_contribution_payment_instrument' => [
          'name' => 'recurring_contribution_payment_instrument',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Recurring Contribution Payment Instrument'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'recurringdonationimporter_fake_entity.recurring_contribution_payment_instrument',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Recurring Contribution Payment Instrument"),
          ],
          'add' => NULL,
        ],
        'recurring_contribution_description' => [
          'name' => 'recurring_contribution_description',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Recurring Contribution Description'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'recurringdonationimporter_fake_entity.recurring_contribution_description',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Recurring Contribution Description"),
          ],
          'add' => NULL,
        ],
        'gocardless_mandate_id' => [
          'name' => 'gocardless_mandate_id',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('GoCardless Mandate Id'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'recurringdonationimporter_fake_entity.gocardless_mandate_id',
          'table_name' => 'recurringdonationimporter_fake_entity',
          'entity' => 'RecurringDonationImporter',
          'bao' => 'CRM_Membershipextrasimporterapi_DAO_RecurringDonationImporter',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("GoCardless Mandate Id"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'recurringdonationimporter_fake_entity', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'recurringdonationimporter_fake_entity', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
